COMANDO_LISTAR_OPERACIONES = "listar_operaciones"
COMANDO_CAMINO_MINIMO = "camino"
COMANDO_DIAMETRO = "diametro"

LISTA_COMANDOS = [
    COMANDO_LISTAR_OPERACIONES,
    COMANDO_CAMINO_MINIMO,
    COMANDO_DIAMETRO
]
