COMANDO_LISTAR_OPERACIONES = "listar_operaciones"
COMANDO_CAMINO_MINIMO = "camino"
COMANDO_DIAMETRO = "diametro"
COMANDO_RANGO = "rango"
COMANDO_NAVEGACION = "navegacion"
COMANDO_CONECTIVIDAD = "conectados"

LISTA_COMANDOS = [
    COMANDO_LISTAR_OPERACIONES,
    COMANDO_CAMINO_MINIMO,
    COMANDO_DIAMETRO,
    COMANDO_RANGO,
    COMANDO_NAVEGACION,
    COMANDO_CONECTIVIDAD
]
